### ISSUE TITLE
[无法下载]3篇PDF无法下载

### ISSUE THREAD

**Issue by YiFlower** [wenbochang888/house#4]

**Comment by YiFlower** [comment]
很高兴能在这里看到关于代码之外的讨论，我最近在知乎上看到关于这篇文章的推荐，在搜索引擎上找到了我想要的内容。但是我在自述文件中复制的下载连接（或者直接点击），都无法下载。希望UP能放一个网盘的链接（希望链接是长久有效的，我预测以后还会有人会有这个问题）。

**Comment by wenbochang888** [comment]
@YiFlower 
你好，github网络国内访问不稳定，导致下载失败。
后续我存放至国内源，会替换相应的链接

感谢提问

**Comment by wenbochang888** [comment]
下载源 已更新至国内的git

**Comment by wenbochang888** [comment]
备用地址：https://share.weiyun.com/0LKz7Qs2

**Comment by wenbochang888** [comment]
> 备用地址：https://share.weiyun.com/0LKz7Qs2

分享被人举报已经失效，采用这个链接下载：
https://hub.fastgit.org/wenbochang888/house
