### ISSUE TITLE
能找到以下帖子吗

### ISSUE THREAD

**Issue by mqliang** [wenbochang888/house#6]
《“征税加息降房价”－荒谬的理论、恐怖的圈套》

作者“孤独的思想”发布于2006。

《房价长期预测专贴：十年内北京四环内的均价会达到八万，兼谈西安的房价及》

作者“北望帝都”发布于2010。

《中国人为什么一套接一套的买房子？》

作者“不炒不热闹”先生发布于2009。

《周五之前应该有一次降准，最晚4月15日之前，最佳日期4月9日》

作者80后60岁走遍全球”先生发布于2015。

对金融政策的预测神准。给出了今后的趋势。高明。

《一个炒房人的终极预测！！！！－－调控将撤底失败》

作者wtwjwk，发布于2010。

以一个炒房者的眼光看中国房价调控，和银行人及上层有交集。分析深刻，预测几乎全部准确。因为不建议炒房，且资金巨大，所以排名往后。

《房地产暴涨的推手：调控的反市场经济学分析》

作者mini_hostess。

作者通今博古，不让须眉。深入分析调控政策实质。指出调控3个手段（1，以抑制投资、投机的名义控制需求，从而阻止资本进入房地产的行业。2、以打击囤地、提高贷款门槛、抬高入市成本、提高市场准入机制等手段打击供给。3、增税），均为造成高房价的原因。可惜被骂，未完，遗憾。

《我做了3年房地产了，我告诉你2014年房价会不会降》

作者茶香竹韵。非常年轻，懂奇门遁甲之术，指出2014年为最佳买房年，准确判断2016年的大涨，也给出了2017以后几年的预测，神奇。

《最后的救市-换入大城市房子的最后时刻》

作者“鹏程蛇口”先生。

作者有几个买房观点，虽属老生常谈，但提纲挈领，有一定参考价值。

特别推荐：

《老公坚持房价会跌，我现在一看房价就满嘴吐血》

作者“爱死小肥羊”。

此帖无宏观大论，也非投资指南，乃购房遭遇和情感经历。一名女孩对名实之家（名义上的家和实质的家）的渴望发自肺腑。数万元价差，终致房梦破灭，情侣别道扬镳，同情唏嘘。此贴荏苒数年，真挚感人。情景仿佛咫尺，悲喜感同身受。斯文伊始，旋引共鸣，和者甚众，俚语谦言，论辩激烈。升斗小民，言买房生活婚姻之市井万象，贯以作者感情之沧海桑田，演绎房市之简约版金瓶梅。高评价。

**Comment by wenbochang888** [comment]
@mqliang 可以爬，贴链接我看一下

**Comment by mqliang** [comment]
《“征税加息降房价”－荒谬的理论、恐怖的圈套》
https://bbs.tianya.cn/post-house-26694-1.shtml

《一个炒房人的终极预测！！！！－－调控将撤底失败》
http://bbs.tianya.cn/post-house-217995-1.shtml

房价长期预测专贴：十年内北京四环内的均价会达到八万，兼谈西安的房价及
https://bbs.tianya.cn/m/post-house-274506-11.shtml

《中国人为什么一套接一套的买房子？》
http://bbs.tianya.cn/post-house-178615-1.shtml

《周五之前应该有一次降准，最晚4月15日之前，最佳日期4月9日》
http://bbs.tianya.cn/post-house-582941-1.shtml

《房地产暴涨的推手：调控的反市场经济学分析》
http://bbs.tianya.cn/post-house-430352-1.shtml

《最后的救市-换入大城市房子的最后时刻》
http://bbs.tianya.cn/post-house-590038-1.shtml

《老公坚持房价会跌，我现在一看房价就满嘴吐血》
http://bbs.tianya.cn/post-house-192177-1.shtml

**Comment by zkailinzhang** [comment]
都访问不了，能发邮箱一份吗   763455447@qq.com
